<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.chenile</groupId>
    <artifactId>chenile-messaging-parent</artifactId>
    <version>${revision}</version>
    <name>Chenile Messaging Parent</name>

    <modules>
        <module>chenile-pub-sub</module>
        <module>cucumber-mqtt-utils</module>
        <module>chenile-mqtt</module>
        <module>cloud-edge-switch</module>
        <module>chenile-kafka</module>
    </modules>

    <packaging>pom</packaging>

    <parent>
        <groupId>org.chenile</groupId>
        <artifactId>chenile-parent</artifactId>
        <version>2.1.7</version>
    </parent>

    <properties>
        <revision>${chenile.messaging.version}</revision>
    </properties>
</project>
